### ISSUE TITLE
size = str(len(txt.encode("utf-8"))) + ":"

### ISSUE THREAD

**Issue by cjjdaq** [alexpdev/pyben#10]
def bencode_str(txt):
    """
    Encode string literals.

    Parameters
    ----------
    txt : `str`
        Any text string.

    Returns
    -------
    `bytes` :
        Bencoded string literal.

    """
    size = str(len(txt.encode("utf-8"))) + ":"
    return size.encode("utf-8") + txt.encode("utf-8")

**Comment by alexpdev** [comment]
Can you please provide more information on the issue you are having?
